[workspace]
members = [".", "wary_derive"]

[package]
name = "wary"
version = "0.0.1"
edition = "2021"

[dependencies]
thiserror = "1"

email_address = { version = "0.2", default-features = false, optional = true }
regex = { version = "1", optional = true }
url = { version = "2", optional = true }
wary_derive = { path = "wary_derive", version = "0.0.1", optional = true }
semver = { version = "1", optional = true }
unicode-segmentation = { version = "1.12.0", optional = true }

[features]
default = ["derive", "full"]
full = ["email", "url", "regex", "semver", "graphemes"]

derive = ["dep:wary_derive"]
email = ["dep:email_address"]
url = ["dep:url"]
regex = ["dep:regex"]
semver = ["dep:semver"]
graphemes = ["dep:unicode-segmentation"]

