[workspace]
members = [".", "derive"]

[package]
name = "wary"
version = "0.0.1"
edition = "2021"

[dependencies]
wary-derive = { path = "derive", version = "0.0.1", optional = true }
email_address = { version = "0.2", default-features = false, optional = true }
thiserror = "1"
url = { version = "2", optional = true }

[features]
default = ["url", "derive"]

derive = ["dep:wary-derive"]
email = ["dep:email_address"]
url = ["dep:url"]

