[workspace]
members = [".", "wary_derive"]

[package]
name = "wary"
version = "0.0.1"
edition = "2021"

[dependencies]
thiserror = "1"

email_address = { version = "0.2", default-features = false, optional = true }
url = { version = "2", optional = true }
wary_derive = { path = "wary_derive", version = "0.0.1", optional = true }

[features]
default = ["derive", "full"]
full = ["email", "url"]

derive = ["dep:wary_derive"]
email = ["dep:email_address"]
url = ["dep:url"]

